hctl: Restore `--version` CLI option
Now `hctl --version` works.

diff --git a/mero-halon/scripts/hctl b/mero-halon/scripts/hctl
--- a/mero-halon/scripts/hctl
+++ b/mero-halon/scripts/hctl
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -eu -o pipefail
 
 # Local version of halonctl. This script attempts to parse sensible
 # values for '-l' and '-a' parameters from the `/etc/sysconfig/halond`
@@ -9,24 +10,22 @@
 
 HALOND_CONF=/etc/sysconfig/halond
 
-if [ -e "$HALOND_CONF" ]; then
-  source "$HALOND_CONF"
+die() { echo "$@" >&2; exit 1; }
+
+if [ "$*" = '--version' ]; then
+    exec halonctl --version
 fi
 
-if [ -z "$HALOND_LISTEN" ]; then
-  echo "HALOND_LISTEN variable not set; please export or add to $HALOND_CONF"
-  die 1
+if [ -e "$HALOND_CONF" ]; then
+    . "$HALOND_CONF"
 fi
+
+[ -n "$HALOND_LISTEN" ] ||
+    die "HALOND_LISTEN variable not set; please export or add to $HALOND_CONF"
 
 IFS=':' read -ra ADDR <<< "$HALOND_LISTEN"
-
 IP=${ADDR[0]}
-
-if [ -z "$IP" ]; then
-  echo "Cannot determine IP ($IP) from $HALOND_LISTEN"
-  die 1
-fi
-
+[ -n "$IP" ] || die "Cannot determine IP ($IP) from $HALOND_LISTEN"
 HALONCTL_LISTEN="$IP:0"
 
-halonctl -l "$HALONCTL_LISTEN" -a "$HALOND_LISTEN" "$@"
+exec halonctl -l "$HALONCTL_LISTEN" -a "$HALOND_LISTEN" "$@"
