generate freeze list

diff --git a/docker/3-halon/build-with-artifacts b/docker/3-halon/build-with-artifacts
--- a/docker/3-halon/build-with-artifacts
+++ b/docker/3-halon/build-with-artifacts
@@ -17,5 +17,14 @@ done
 find . -name \*.log -type f | while read l ; do \
   cp -v $l /halon/artifacts/logs/ ; \
 done
+
+if [ "$RC" == "0" ] ; then
+  # we build OK, so check freeze
+  # and use the return code from
+  # that as overall exit
+  make check-freeze
+  RC=$?
+fi
+
 exit $RC
 
