Remove cabal-freeze test until issues with circleci are fixed.
- `inline-c` is only needed when compiling with USE_MERO=1
- Need to not complain on deps which are listed but not needed.

diff --git a/docker/3-halon/build-with-artifacts b/docker/3-halon/build-with-artifacts
--- a/docker/3-halon/build-with-artifacts
+++ b/docker/3-halon/build-with-artifacts
@@ -3,9 +3,9 @@
 export DC_HOST_IP=$( /sbin/ifconfig eth0 | grep "inet " | sed 's/^.*inet \([.0-9]*\) .*$/\1/')
 export DC_VERBOSE=1
 
-echo whoami: 
+echo whoami:
 whoami
- 
+
 echo iptables is
 iptables -L -v
 
@@ -32,13 +32,14 @@ find . -name \*.log -type f | while read l ; do \
   cp -v $l /halon/artifacts/logs/ ; \
 done
 
-if [ "$RC" == "0" ] ; then
-  # we build OK, so check freeze
-  # and use the return code from
-  # that as overall exit
-  make check-freeze
-  RC=$?
-fi
+# 2015-07-14 NC - comment this out until we can resolve `inline-c` issues.
+# if [ "$RC" == "0" ] ; then
+#   # we build OK, so check freeze
+#   # and use the return code from
+#   # that as overall exit
+#   make check-freeze
+#   RC=$?
+# fi
 
 if [ "$RC" == "0" ] ; then
   make coverage
